import Head from 'next/head'
import Landingpage from './components/landingpage';
import { Inter } from '@next/font/google';
import Iconspage from './components/iconspage';
import Testimonial from './components/testimonial';
import Card  from  './components/cards';
import Form from './components/form';
import About from './components/about';

import { motion } from "framer-motion";



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main  initial={{ x: 300, opacity: 20 }}
    animate={{ x: 0, opacity: 10 }}
    exit={{ x: 300, opacity: 20 }}
    transition={{
      type: "spring",
      stiffness: 260,
      damping: 20,
    }}>
        <Landingpage />
        <Iconspage />
        <Testimonial />
        <Card />
        <Form />
        <About />
      </motion.main>
    </>
  )
}
